package com.adammcneilly.magicmirror.weather.models

data class ForecastData(
        val time: Long? = null,
        val summary: String? = null,
        val icon: String? = null,
        val sunriseTime: Long? = null,
        val sunsetTime: Long? = null,
        val moonPhase: Float? = null,
        val precipIntensity: Float? = null,
        val precipIntensityMax: Float? = null,
        val precipIntensityMaxTime: Long? = null,
        val precipProbability: Float? = null,
        val precipType: String? = null,
        val temperature: Float? = null,
        val temperatureHigh: Float? = null,
        val temperatureLow: Float? = null,
        val apparentTemperatureHigh: Float? = null,
        val apparentTemperatureHighTime: Long? = null,
        val apparentTemperatureLow: Float? = null,
        val apparentTemperatureLowTime: Long? = null,
        val dewPoint: Float? = null,
        val humidity: Float? = null,
        val pressure: Float? = null,
        val windSpeed: Float? = null,
        val windGust: Float? = null,
        val windGustTime: Long? = null,
        val windBearing: Int? = null,
        val cloudCover: Float? = null,
        val uvIndex: Int? = null,
        val uvIndexTime: Long? = null,
        val visibility: Float? = null,
        val ozone: Float? = null,
        val temperatureMin: Float? = null,
        val temperatureMinTime: Long? = null,
        val temperatureMax: Float? = null,
        val temperatureMaxTime: Long? = null,
        val apparentTemperatureMin: Float? = null,
        val apparentTemperatureMinTime: Long? = null,
        val apparentTemperatureMax: Float? = null,
        val apparentTemperatureMaxTime: Long? = null
)